### ISSUE TITLE
v 2.6.2 geometry validation doesn't work

### ISSUE THREAD

**Issue by kaiverge** [bjornharrtell/jsts#435] opened 2021-06-03 20:58 UTC
e.g.

   const g = reader.read({
                type: 'Feature',
                geometry: {
                    type: 'Polygon',
                    coordinates: coor
                }
            });
            //
            g.geometry.isValid()  always false while with previous ersion is just fine

**Comment by kaiverge** [comment] 2021-06-03 21:36
open layers v. 6.5.0

**Comment by bjornharrtell** [comment] 2021-06-03 23:42
Please provide a more complete example. And with previous version do you mean 2.6.1?

**Comment by kaiverge** [comment] 2021-06-04 13:18
yes, in 2.6.1 it works just fine. 

  const reader = new jsts.io.GeoJSONReader();
            var coor = (feature.getGeometry() as any).getCoordinates();
            const g = reader.read({
                type: 'Feature',
                geometry: {
                    type: 'Polygon',
                    coordinates: coor
                }
            });
            
            if (!(g as any).geometry.isValid())  // in version 2.6.1 it works in v 2.6.2 it always returns invalid

**Comment by kaiverge** [comment] 2021-06-07 15:00
it returns invalid for any simple single shape (e.g. rectangular)

**Comment by bjornharrtell** [comment] 2021-06-07 15:48
With https://github.com/bjornharrtell/jsts/commit/7eee7746998920049d270c234674f683c11332d5 I've added a couple of test cases to verify IsValidOp behaviour and cannot reproduce any issue with it, so you will have to come up with something more reproducable. For example you are not disclosing the actual geometry that you claim is valid.

Also I see you are using the jsts namespace object which is really only intended for the single file build and as mentioned in Caveats on in the main README shortcut methods are not available unless using the bundled version so I'm actually not sure how come your code works at all. Try to importing and using IsValidOp directly instead.

**Comment by gvdhorst** [comment] 2021-06-07 16:17
I think the problem is with the GeoJSON reader.

The following code:
`const jsts = require('jsts');`
`const testGeometry = { type: 'Polygon', coordinates: [[[1, 1], [1, 2], [2, 1], [1, 1]]] };`
`console.log(new jsts.io.GeoJSONReader().read(testGeometry).getCoordinates());`

Yields this in v2.6.1:
>[
>  m { x: 1, y: 1, z: NaN },
>  m { x: 1, y: 2, z: NaN },
>  m { x: 2, y: 1, z: NaN },
>  m { x: 1, y: 1, z: NaN }
>]

But this in v2.6.2:
> [
>  m { x: null, y: null, z: null },
>  m { x: null, y: null, z: null },
>  m { x: null, y: null, z: null },
>  m { x: null, y: null, z: null }
>]

**Comment by bjornharrtell** [comment] 2021-06-07 18:23
Thanks @gvdhorst I think you are right and likely a regression caused by https://github.com/bjornharrtell/jsts/commit/4b77e67bf12182770ae211fd1f88735d56c69a5c. I'll see what I can do..

**Comment by kaiverge** [comment] 2021-06-08 20:57
FULL CODE

import * as jsts from 'jsts';



            const reader = new jsts.io.GeoJSONReader();
            var coor = (feature.getGeometry() as any).getCoordinates();

![image](https://user-images.githubusercontent.com/59927573/121256483-d8d6a900-c869-11eb-89cf-d3f5cbd20919.png)


            const g = reader.read({
                type: 'Feature',
                geometry: {
                    type: 'Polygon',
                    coordinates: coor
                }
            });
            //
            if (!(g as any).geometry.isValid())

**Comment by bjornharrtell** [comment] 2021-06-11 11:46
Should be fixed as of JSTS 2.7.0

**Closed by bjornharrtell** 2021-06-11 11:46 UTC
