### ISSUE TITLE
unable to use jsts with Node

### ISSUE THREAD

**Issue by mperdikeas** [bjornharrtell/jsts#473] opened 2022-07-27 09:46 UTC
I am trying to use the [JSTS][1] NPM library in a Node / TypeScript project.

I've followed the instructions given [here][2].
When I try to import a module like so:

    import GeoJSONReader from 'jsts/org/locationtech/jts/io/GeoJSONReader.js'

I get:

> TSError: ⨯ Unable to compile TypeScript: src/index.ts:1:27 - error
> TS7016: Could not find a declaration file for module
> 'jsts/org/locationtech/jts/io/GeoJSONReader.js'.
> '/home/username/test/node_modules/jsts/org/locationtech/jts/io/GeoJSONReader.js'
> implicitly has an 'any' type.   Try `npm i --save-dev @types/jsts` if
> it exists or add a new declaration (.d.ts) file containing `declare
> module 'jsts/org/locationtech/jts/io/GeoJSONReader.js';`
> 
> 1 import GeoJSONReader from
> 'jsts/org/locationtech/jts/io/GeoJSONReader.js'

I tried both suggestions but the error message remains the same. I am using:

     $ npm --version
     8.15.0
     $ node -v
     v14.20.0

Code is simply:

    import GeoJSONReader from 'jsts/org/locationtech/jts/io/GeoJSONReader.js'
    console.log('hello World!');

`tsconfig.json` is:

    {
      "compilerOptions": {
    
        "target": "es2016",                      
        "lib": ["es6"],                          
    
        "module": "commonjs",                    
        "rootDir": "src",                        
        "resolveJsonModule": true,               
    
        "allowJs": true,                         
        "outDir": "build",                       
        "esModuleInterop": true,                 
        "forceConsistentCasingInFileNames": true,
    
        "strict": true,                          
        "noImplicitAny": true,                   
        "skipLibCheck": true                     
      }
    }

`package.json` is:

    {
      "name": "archetype-ts-node",
      "version": "1.0.0",
      "description": "",
      "main": "index.js",
      "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1",
        "build": "tsc",
        "_raze": "rimraf ./node_modules",
        "clean": "rimraf ./build",
        "raze": "run-s clean _raze",
        "exec": "npx ./build/index.js",
        "start": "run-s build exec ",
        "start:dev": "nodemon"
      },
      "repository": {
        "type": "git",
        "url": "git+https://github.com/mperdikeas/archetype-ts-node.git"
      },
      "keywords": [],
      "author": "",
      "license": "ISC",
      "bugs": {
        "url": "https://github.com/mperdikeas/archetype-ts-node/issues"
      },
      "homepage": "https://github.com/mperdikeas/archetype-ts-node#readme",
      "devDependencies": {
        "@types/node": "^18.0.3",
        "nodemon": "^2.0.19",
        "npm-run-all": "^4.1.5",
        "rimraf": "^3.0.2",
        "ts-node": "^10.8.2",
        "typescript": "^4.7.4"
      },
      "dependencies": {
        "jsts": "^2.9.0"
      }
    }

  [1]: https://github.com/bjornharrtell/jsts
  [2]: https://github.com/bjornharrtell/jsts#readme

**Comment by bjornharrtell** [comment] 2022-07-27 12:50
It's not a node issue it's due to that jsts does not have typescript type declaration, so this is a duplicate of https://github.com/bjornharrtell/jsts/issues/285.

You can force it to work by lifting for restriction or write type declaration for the parts you use.

**Closed by bjornharrtell** 2022-07-27 12:50 UTC

**Comment by mperdikeas** [comment] 2022-07-27 16:32
You can't just force this to work. Adding a `//@ts-expect-error` to silence the TypeScript, i.e. like so:

    // @ts-expect-error
    import GeoJSONReader from 'jsts/org/locationtech/jts/io/GeoJSONReader.js'
    const r = new GeoJSONReader();

... results in the following error which is very confusing as it asks you to use `import` where in fact the code does use `import`.

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/mperdikeas/test/node_modules/jsts/org/locationtech/jts/io/GeoJSONReader.js
require() of ES modules is not supported.
require() of /home/mperdikeas/test/node_modules/jsts/org/locationtech/jts/io/GeoJSONReader.js from /home/mperdikeas/test/src/index.ts is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename GeoJSONReader.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/mperdikeas/test/node_modules/jsts/package.json.

    at new NodeError (internal/errors.js:322:7)
    at Module._extensions..js (internal/modules/cjs/loader.js:1102:13)
    at Object.require.extensions.<computed> [as .js] (/home/mperdikeas/test/node_modules/ts-node/src/index.ts:1587:43)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/mperdikeas/test/src/index.ts:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module.m._compile (/home/mperdikeas/test/node_modules/ts-node/src/index.ts:1597:23) {
  code: 'ERR_REQUIRE_ESM'
}

```

**Comment by bjornharrtell** [comment] 2022-07-28 08:59
Ok but I was rather thinking there is a compiler option that can allow untyped dependencies, but I'm not entirely sure. If there is no such way I suppose the only fix is to follow the suggestion:

add a new declaration (.d.ts) file containing declare module 'jsts/org/locationtech/jts/io/GeoJSONReader.js';
