### ISSUE TITLE
Envelope instanceof test makes quadtree insert fail

### ISSUE THREAD

**Issue by Pieter-Jan** [bjornharrtell/jsts#243] opened 2016-03-30 08:24 UTC
Hello,

The following line is causing problems for me with Quadtree in the latest release:

`index.quadtree.insert(info.indexPoly.getEnvelopeInternal(), self);`

indexPoly is a jsts polygon object. I tracked down this rather strange bug:

on line 226 in Envelope.js there is this check: 

`if (arguments[0] instanceof Envelope) {`

Yet if arguments[0] is also of the Envelope type, this check fails, resulting in contains returning "undefined". 

This results in the assertion in line 30 of Root.js to return false: 		

`Assert.isTrue(tree.getEnvelope().contains(itemEnv));`

Can you please figure out what is going on here? Thanks!

**Comment by bjornharrtell** [comment] 2016-03-31 05:32
I see no real difference with the simple test I got for Quadtree at https://github.com/bjornharrtell/jsts/blob/master/test/manual/index/quadtree/Quadtree.js and it passes with no problems as far as I know. So, I don't know how to reproduce this problem or what could be the cause.

**Comment by bjornharrtell** [comment] 2016-04-04 20:43
@Pieter-Jan, can you provide a test that demonstrates this issue?

**Comment by bjornharrtell** [comment] 2016-04-07 20:58
Closing as I cannot reproduce without further information.

**Closed by bjornharrtell** 2016-04-07 20:58 UTC
