### ISSUE TITLE
Geojson Feature failed to be loaded

### ISSUE THREAD

**Issue by blackrez** [bjornharrtell/jsts#256] opened 2016-04-10 08:07 UTC
Hello,

I upgraded to the last jsts version and I can't load a geojson with a feature .

```javascript
p = {
  "type": "Feature",
  "geometry": {
    "type": "Point",
    "coordinates": [125.6, 10.1]
  },
  "properties": {
    "name": "Dinagat Islands"
  }
}
var reader = new jsts.io.GeoJSONReader();
reader.read(p)
TypeError: Cannot read property 'Feature' of undefined
    at bi.e.read (/home/nabil/studio/stuff/node_modules/jsts/dist/jsts.min.js:15:1048)
    at Oi.e.read (/home/nabil/studio/stuff/node_modules/jsts/dist/jsts.min.js:15:4370)
    at repl:1:8
    at REPLServer.defaultEval (repl.js:248:27)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:412:12)
    at emitOne (events.js:82:20)
    at REPLServer.emit (events.js:169:7)
    at REPLServer.Interface._onLine (readline.js:210:10)
    at REPLServer.Interface._line (readline.js:549:8)
```

**Comment by bjornharrtell** [comment] 2016-04-10 12:26
As stated by http://bjornharrtell.github.io/jsts/1.1.0/doc/GeoJSONReader.html the read method expects a GeoJSON Geometry not a Feature. This is also a duplicate of #249. Perhaps I need to add a better error message for this case...

**Comment by bjornharrtell** [comment] 2016-04-10 12:31
On second thought I see that parsing feature to geometries indeed was supported by the 0.x versions, so I'll consider fixing it for the next version.

**Closed** 2016-04-14 09:30 UTC
