### ISSUE TITLE
geomgraph and other namespaces no longer exposed.

### ISSUE THREAD

**Issue by 3choBoomer** [bjornharrtell/jsts#275] opened 2016-07-01 19:01 UTC
I was previously using 0.17 of jsts and I had access to the `geomgraph` classes.

I am in the process of upgrading to 1.1.2 to fix some of the `isValid` and `isSimple` bug fixes surrounding duplicate points, and now `geomgraph` is no longer exported.

Is this by design?

![jsts0 17 0](https://cloud.githubusercontent.com/assets/521828/16531882/2cecacf6-3f94-11e6-92d7-b555355a89cd.PNG) ![jsts1 1 2](https://cloud.githubusercontent.com/assets/521828/16531885/311f63d6-3f94-11e6-984a-6b74b00eb749.PNG)

**Comment by bjornharrtell** [comment] 2016-07-02 16:23
It's not missing by design. Will consider exposing more stuff in the next release.

**Comment by 3choBoomer** [comment] 2016-07-05 15:57
In the meantime, is there another way of recreating this functionality now that `geomgraph` and `ConsistentAreaTester` are not exposed?

```
    var coordinates = convertGeoJsonToJTS(geoJsonPolygon);
    var geometryFactory = new jsts.geom.GeometryFactory();
    var shell = geometryFactory.createLinearRing(coordinates);
    var jstsPolygon = geometryFactory.createPolygon(shell);

    // if the geometry is aleady a simple linear ring, do not
    // try to find self intersection points.
    var validator = new jsts.operation.IsSimpleOp(jstsPolygon);
    if (validator.isSimpleLinearGeometry(jstsPolygon)) {
      return;
    }

    var res = [];
    var graph = new jsts.geomgraph.GeometryGraph(0, jstsPolygon);
    var cat = new jsts.operation.valid.ConsistentAreaTester(graph);
    var r = cat.isNodeConsistentArea();
    if (!r) {
      var pt = cat.getInvalidPoint();
      res.push([pt.x, pt.y]);
    }
```

**Comment by bjornharrtell** [comment] 2016-07-05 17:04
Fixed in master. Planning to release 1.2.0 in a near future.

**Closed by bjornharrtell** 2016-07-05 17:04 UTC
