### ISSUE TITLE
MultiPoint does not support getEnvelopeInternal

### ISSUE THREAD

**Issue by rbrundritt** [bjornharrtell/jsts#232] opened 2016-02-24 07:48 UTC
Tried to see if a polygon covered a Multipoint and found that this function errored because Multipoint doesn't seem to support getEnevlopeInternal. Not certain why this is happening. Looks like there is a function there.

**Comment by bjornharrtell** [comment] 2016-02-24 12:43
I cannot reproduce. I've commited two test cases proving it works. Can you provide more details, perhaps a code example?

**Comment by bjornharrtell** [comment] 2016-02-24 19:53
Closing for now. Reopen if issues remain in rc7 and provide more details if possible.

**Closed by bjornharrtell** 2016-02-24 19:53 UTC

**Comment by rbrundritt** [comment] 2016-02-24 20:42
Just tested in rc7 and still seeing it. Here is a simple code sample that keeps crashing:

`var multipoint = new jsts.geom.GeometryFactory().createMultiPoint([new jsts.geom.Coordinate(0, 0), new jsts.geom.Coordinate(10, 10)]);
var env2 = multipoint.getEnvelopeInternal();`

**Comment by bjornharrtell** [comment] 2016-02-24 21:08
Ah, there is an issue with overload resolution for the createMultiPoint method because the type overload in this case is on different array types which has lost that type information in JavaScript. The JavaScript logic will always assume it's a Point, as you discovered. I've actually added createMultiPointFromCoords to JTS as a workaround. I can see this is a cause of confusion and should be documented somewhere but I've got not place for that yet.
